### ISSUE TITLE
Error on queries on tables with special characters in their names

### ISSUE THREAD

**Issue by andyg75** [fsprojects/DynamoDb.SQL#24]
I tried querying a table with a "." in it's name. I get the following error: "Expecting: 'where' (case-insensitive)". I get the same error when the table has a hyphen in its name.

I tried using brackets around the table name, as one would do in a SQL client. No luck. I get this error in that case: "Expecting: table name"

**Comment by theburningmonk** [comment]
This was fixed by this PR : https://github.com/fsprojects/DynamoDb.SQL/pull/22 I just haven't got around to adding some other features I wanted for the next release.

I'll do an intermediate release shortly that includes a fix for that.

**Comment by andyg75** [comment]
Thanks, apologies for the dupe. This looks like a really great app.

**Comment by theburningmonk** [comment]
pushed a new package which should allow those special characters
