### ISSUE TITLE
Querying on index with very long number

### ISSUE THREAD

**Issue by zairnamlas** [fsprojects/DynamoDb.SQL#29]
Hi Yan,
This could be the same as I mentioned before which you fixed it with long numbers. This time when I'm querying on index with a long number then it is not returning any results and with small number it does. I debugged it a little and found that it is jumping one number up. Following is the query I'm trying and the snapshot of the converted filter

This works
SELECT * FROM pd_cs_friendshiprequest WHERE ForUserId = 578318698 WITH(Index(ForUserIdIndex, false), NoConsistentRead)

This doesn't work
SELECT * FROM pd_cs_friendshiprequest WHERE ForUserId = 10205471065416239 WITH(Index(ForUserIdIndex, false), NoConsistentRead)

http://screencast.com/t/Ti4tizS51

I guess, it will be again a simple fix while converting string to number.
Hoping to hear from you soon.

**Comment by theburningmonk** [comment]
I suspect in this case it might be that you're running into a case where you start to lose precisions with floating point. e.g. 

I get these in LinqPad:

```
	double a = 10205471065416239;
	double b = 10205471065416240;
	double c = 10205471065416241;
	double d = 10205471065416242;
	
	double e = 10205471065416056;
	double f  = 10205471065416057;
	
	a.ToString("r").Dump(); // 10205471065416240
	b.ToString("r").Dump(); // 10205471065416240
	c.ToString("r").Dump(); // 10205471065416240
	d.ToString("r").Dump(); // 10205471065416242
	e.ToString("r").Dump(); // 10205471065416056
	f.ToString("r").Dump();  // 10205471065416056
```

So looks like we may not have solved the problem the last time around.

In .Net we're somewhat limited with what we can do with a 64-bit `double`, but in cases where there is no decimals we can get away with using a `BigInteger`.

How is the key represented in your code? Are they stored as a int64?

**Comment by zairnamlas** [comment]
Yeah, they are "long". I've discovered that precesion go out when the long is even.

**Comment by theburningmonk** [comment]
ok, thanks, I think I know what to do here - use `BigInteger` when there's no decimal - to solve this

**Comment by zairnamlas** [comment]
Sounds good.

**Comment by theburningmonk** [comment]
@zairnamlas - did the fix work for you guys? If so, I'll close the issue

**Comment by zairnamlas** [comment]
Yeah, it looks like ok. It is fetching results now. Thanks Yan.
